version: '3.9'
services:
  db:
    container_name: rsschool-nodejs_db
    build: ./src/common/db/
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Europe/Minsk
    networks:
      - custom_network
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    container_name: rsschool-nodejs_node-web-app
    build: ./
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      PORT: ${PORT}
      TZ: Europe/Minsk
    networks:
      - custom_network
    volumes:
      - ./build:/usr/app/build
      - app_volume:/usr/app/logs
    env_file:
      - .env

volumes:
  db_volume:
  app_volume:

networks:
  custom_network:
    driver: bridge
