import { BaseEntity, Entity, PrimaryColumn, Column as ColumnType } from 'typeorm';
import { Column } from '../columns/column.model';

const { v4: uuidv4 } = require('uuid');

export interface IBoard {
  id?: string;
  title?: string;
  columns?: Column[];
}
/**
 * Creates board
 * @type {Board}
 * @param {Object} object containing board
 * @param {String} board id (auto-generated by uuid by default)
 * @param {String} board title
 * @param {Array<Column>} board columns
 */

@Entity({name: 'Board'})
export class Board extends BaseEntity implements IBoard {
  @PrimaryColumn('varchar', {length: 100})
  id: string;

  @ColumnType('varchar', {length: 100})
  title: string;

  @ColumnType('varchar', {length: 100})
  columns: Array<Column>;

  constructor({
    id = uuidv4(),
    title = 'ButterBoard',
    columns = [new Column()]
  } = {}) {
    super();
    this.id = id;
    this.title = title;
    this.columns = columns;
  }
}
