const { v4: uuidv4 } = require('uuid');
const Column = require('../columns/column.model');

/**
 * Creates board instance
 * @type {Board}
 * @param {Object} [props={}] object containing board properties
 * @param {String} [props.id] board id (auto-generated by uuid by default)
 * @param {String} [props.title = 'Board Title'] board title
 * @param {Array<Column>} [props.columns = [Column]] board columns
 */
class Board {
  constructor({
    id = uuidv4(),
    title = 'ButterBoard',
    columns = new Column()
  } = {}) {
    this.id = id;
    this.title = title;
    this.columns = columns;
  }
}

module.exports = Board;
