const { v4: uuidv4 } = require('uuid');
import { Column } from '../columns/column.model';

export interface IBoard {
  id?: string;
  title?: string;
  columns?: Column[];
}
/**
 * Creates board
 * @type {Board}
 * @param {Object} object containing board
 * @param {String} board id (auto-generated by uuid by default)
 * @param {String} board title
 * @param {Array<Column>} board columns
 */
export class Board implements IBoard {
  id: string;
  title: string;
  columns: Column[];

  constructor({
    id = uuidv4(),
    title = 'ButterBoard',
    columns = [new Column()]
  } = {}) {
    this.id = id;
    this.title = title;
    this.columns = columns;
  }
}
